apiVersion: v1
kind: Secret
metadata:
  name: pg-backup-secrets
type: Opaque
data:
  AWS_S3_ACCESS_KEY_ID: cmVwbGFjZS1tZQ==
  AWS_S3_SECRET_ACCESS_KEY: cmVwbGFjZS1tZQ==
  DATABASE_USER: InJlcGxhY2UtbWUi
  DATABASE_PASSWORD: cmVwbGFjZS1tZQ==
  ENCRYPTION_KEY: cmVwbGFjZS1tZQ==
