apiVersion: v2
name: pg-backup
version: 1.0.0
appVersion: 1.0.0
description: This Chart deploys pg-backup CronJob to backup a PostgreSQL database, encrypt, push to S3 and send a webhook notification.
