apiVersion: v1
kind: Secret
metadata:
  name: pg-backup-secrets
type: Opaque
data:
  AWS_S3_ACCESS_KEY_ID: {{ .Values.secrets.AWS_S3_ACCESS_KEY_ID }}
  AWS_S3_SECRET_ACCESS_KEY: {{ .Values.secrets.AWS_S3_SECRET_ACCESS_KEY }}
  DATABASE_USER: {{ .Values.secrets.DATABASE_USER }}
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD }}
  ENCRYPTION_KEY: {{ .Values.secrets.ENCRYPTION_KEY }}
